name: org_eventos_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.9
  
  flutter_localizations: 
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.4.0
  localization: ^2.1.0
  flutter_svg: ^1.0.3
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  mask_text_input_formatter: ^2.1.0
  dio: ^4.0.6

  flutter_polyline_points: ^0.2.6
  
  flutter_onboard: ^2.0.0
  google_maps_flutter: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8

flutter:

  uses-material-design: true

  assets:
   - lib/assets/
   - lib/assets/i18n/
   - lib/assets/images/
